chore(ci): install nodejs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -31,6 +31,12 @@ jobs:
           sudo sh -c "wget -q https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm"
           sudo chmod +x /usr/local/bin/helm
 
+          # Install node.js
+          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
+          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
+          sudo apt-get update || true # circleci fails on update sometimes, but we good
+          sudo apt-get install yarn
+
           # debug
           echo "Version Information: (docker, helm, kubectl)"
           docker version
